services:
  - type: web
    name: honey-pot-api
    payload:
      # Start command for Uvicorn
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    env: python
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_KEY
        generateValue: true
      - key: MISTRAL_API_KEY
        sync: false  # You must provide this in dashboard
